"""Produce ``demo/predictions.json`` by running the real agent in deterministic mode.

    python scripts/bake_demo.py

Every case is generated by the code in this repository with no API key
(heuristic router, template synthesizer, hash embeddings, lexical reranker), and
the JSON says so. The static demo page replays these when no backend is running.
"""

from __future__ import annotations

import asyncio
import datetime as dt
import json
import subprocess
from pathlib import Path
from typing import Any

from src import __version__
from src.agents.orchestrator import build_graph, next_session_state, run_turn
from src.agents.runtime import build_runtime
from src.config import get_settings
from src.observability import configure_logging
from src.session.cache import SessionState

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "demo" / "predictions.json"

SINGLE_CASES: list[dict[str, str]] = [
    {"title": "Lookup", "message": "Heinz ketchup 397 gram bottle"},
    {"title": "Semantic", "message": "healthy breakfast for kids"},
    {"title": "Comparative", "message": "top rated cereals under $5"},
    {"title": "Cheapest", "message": "cheapest coffee"},
    {"title": "Refund > $100", "message": "refund my $200 order from last week"},
    {"title": "Order status", "message": "where is my order #1001"},
    {"title": "Escalation", "message": "this is unacceptable, get me your manager"},
]

CONVERSATION: list[str] = [
    "hi",
    "lactose free milk gallon",
    "add 2 of the second one to my cart",
    "add the almond milk too",
    "remove the almond milk from my cart",
    "what's in my cart",
    "refund the milk",
]


def _sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
            cwd=ROOT,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def _serialise(resp: Any) -> dict[str, Any]:
    return {
        "intent": resp.intent,
        "confidence": resp.confidence,
        "response": resp.response,
        "retrieved_products": [
            {
                "product_id": p.product_id,
                "product_name": p.product_name,
                "aisle": p.aisle,
                "department": p.department,
                "price_usd": p.price_usd,
                "avg_rating": p.avg_rating,
                "score": round(p.score, 4),
                "source": p.source,
            }
            for p in resp.retrieved_products
        ],
        "cart_snapshot": [c.model_dump() for c in resp.cart_snapshot],
        "cart_action": resp.cart_action,
        "escalated": resp.escalated,
        "latency_ms": resp.latency_ms,
        "cost_usd": resp.cost_usd,
        "llm_used": resp.llm_used,
    }


async def bake() -> dict[str, Any]:
    """Run the cases through the offline runtime."""
    configure_logging("WARNING")
    settings = get_settings()
    rt = await build_runtime(settings)
    rt.graph = build_graph(rt)
    singles = []
    for case in SINGLE_CASES:
        resp, _ = await run_turn(
            rt.graph,
            session_id=f"demo-{case['title']}",
            user_id="demo-user",
            message=case["message"],
        )
        singles.append({**case, **_serialise(resp)})
    session = SessionState()
    turns = []
    for message in CONVERSATION:
        resp, state_out = await run_turn(
            rt.graph,
            session_id="demo-conversation",
            user_id="demo-user",
            message=message,
            session=session,
        )
        session = next_session_state(session, resp, state_out)
        turns.append({"message": message, **_serialise(resp)})
    await rt.close()
    return {
        "project": "conversational-ecommerce-assistant",
        "version": __version__,
        "generated_at": dt.datetime.now(dt.UTC).isoformat(timespec="seconds"),
        "git_sha": _sha(),
        "mode": "deterministic fallback (no ANTHROPIC_API_KEY): heuristic router, template synthesizer, hash embeddings, lexical reranker",
        "llm_used": False,
        "model_when_live": settings.anthropic_model,
        "catalog": "synthetic (213 products, seed 20260516)",
        "endpoint": "POST /api/chat",
        "single_cases": singles,
        "conversation": turns,
    }


def main() -> int:
    """Write the JSON file."""
    doc = asyncio.run(bake())
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"wrote {OUT} ({len(doc['single_cases'])} cases, {len(doc['conversation'])} turns)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
